### ISSUE TITLE
Packaging issue

### ISSUE THREAD

**Issue by y3request** [fpaezf/cs2-vpk-map-packer#1]
_Your tools are very cool and helpful.
thank you for making them I use a few._

Although I don't know if I am doing something wrong or it is your tool.
When I use a 7zip plugin to look at a vpk file that hammer compiles. 
They always start like this:
`\fy_mapname.vpk\maps\fy_mapname\`

When I compile with your tool, my map will not load.
The file system after using your tool starts here:
`\fy_mapname.vpk\fy_mapname\`

If your compiler would put them like the default maybe it will load?

Again maybe I am doing something wrong....

edit- pretty sure thats what was causing it, i used the buggy 7-zip plugin to point to the correct file system. It worked.

**Comment by fpaezf** [comment]
Hi!, thank you!

You have to compile your map with hammer, then unpack it to your desktop in a folder, add materials, models or whatever and then repack it with this tool.

Tell me how are you doing that to look for a fix.

Best regards.

**Comment by y3request** [comment]
I already got a compile that uploaded and worked.

When I use your tool, upload to workshop. For some reason the map wont load on my server.
When I use 7-zip plugin to pack my map, after workshop push I can load my map on my server.

I can successfully use your tool, but for some reason it just wont load my after workshop upload.

Again I am very new to mapping. So maybe I am making a mistake LOL.

**Comment by fpaezf** [comment]
You are doing something wrong, i use my tools to pack/unpack and all maps i've uploaded to workshop works flawless. Use the 7zip solution if it works best for you.
