### ISSUE TITLE
Source directory issues

### ISSUE THREAD

**Issue by Closure-2271** [fpaezf/cs2-vpk-map-packer#2]
Hi i got a question when i try to package my map. idk why it cant get map files.But if i drag it into MapPacker.exe it show me FAIL: only 1 argument detected!
Sorry to disturb,this is first time i use source2 so i have much things to learn XD
![image](https://github.com/fpaezf/cs2-vpk-map-packer/assets/156566298/add5f8c8-eb8d-46c6-9e9e-27044f335492)

**Comment by fpaezf** [comment]
You're specifying a file, not a folder in the first parameter. This is why it fails.

**Comment by Closure-2271** [comment]
> You're specifying a file, not a folder in the first parameter. This is why it fails.↳

I ask a really dumb question haha.Thx for your reply now it worked!
